# BungeePortals configuration file, visit www.spigotmc.org/resources/bungeeportals.19 for help.
SaveTask:
  Enabled: false
  Interval: 600
NoPortalPermissionMessage: '&cGet out of here punk. This is invite only. {destination}.'
